/home/administrator/foo/foo.txt
/home/administrator/bar/baz.txt.gpg
/home/administrator/github/memoryspace/test.txt.gpg
/Users/somelaptop/github/memoryspace/abc.txt.gpg
/home/administrator/github/memoryspace/encryptiontest.txt.gpg
/home/administrator/memoryspace/github/shreddingtest.txt.gpg
/home/administrator/github/memoryspace/shreddingtest.txt.gpg
/home/administrator/github/memoryspace/shreddingtest2.txt.gpg
